[Urban Dynamics]
source            = imaps+xoauth2://WORK_EMAIL@outlook.office365.com?
source-cred-cmd   = oama access WORK_EMAIL
outgoing          = smtp+xoauth2://WORK_EMAIL@outlook.office365.com:587
outgoing-cred-cmd = oama access WORK_EMAIL
default           = INBOX
from              = Matthew Benson <WORK_EMAIL>
copy-to           = Sent
cache-headers     = true
