# TODO: can we reconfigure SSH in a way that this isn't needed? Currently colors are wrong over SSH.
# https://github.com/helix-editor/helix/discussions/6963
[editor]
shell = ["fish", "-c"]
true-color = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
